export const ERROR_CODE = {
  // AUTHENTICATION
  AUTHENTICATION_USER_NOT_FOUND: 'AUTHENTICATION_USER_NOT_FOUND',
  // ROLE
  ROLE_NAME_ALREADY_EXIST: 'ROLE_NAME_ALREADY_EXIST',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  // API
  API_PATH_ALREADY_EXIST: 'API_PATH_ALREADY_EXIST',
  API_NOT_FOUND: 'API_NOT_FOUND',
  // PERMISSION
  PERMISSION_NAME_ALREADY_EXIST: 'PERMISSION_NAME_ALREADY_EXIST',
  // ACCOUNT
  ACCOUNT_PHONE_OR_EMAIL_ALREADY_EXIST: 'ACCOUNT_PHONE_OR_EMAIL_ALREADY_EXIST',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_PASSWORD_NOT_MATCH: 'ACCOUNT_PASSWORD_NOT_MATCH',
  // ACCOUNT_ROLE
  ACCOUNT_ROLE_ALREADY_HAS_ROLE: 'ACCOUNT_ROLE_ALREADY_HAS_ROLE',
  // ROLE_PERMISSION_PAIR
  ROLE_PERMISSION_PAIR_ALREADY_EXIST: 'ROLE_PERMISSION_PAIR_ALREADY_EXIST',
};
